wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.7.6
batch_size:
  desc: null
  value: 32
data_root:
  desc: null
  value: ../input/cassava-leaf-disease-classification
debug:
  desc: null
  value: true
fold:
  desc: null
  value: 0
img_size:
  desc: null
  value: 320
lr:
  desc: null
  value: 0.001
model:
  desc: null
  value: resnext50_32x4d
num_epochs:
  desc: null
  value: 2
num_workers:
  desc: null
  value: 4
pin_memory:
  desc: null
  value: true
pretrained:
  desc: null
  value: true
project:
  desc: null
  value: cassava-leaf-disease-classification
run_name:
  desc: null
  value: try-xxx
seed:
  desc: null
  value: 1234
verbose:
  desc: null
  value: true
